import type { Metadata } from 'next';

import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-dvh">
      <body className={inter.className + ' h-full'}>
        <main className="container mx-auto h-full py-2">{children}</main>
      </body>
    </html>
  );
}
