import type { Metadata } from 'next';

import './globals.css';
import { dir } from 'i18next';
import React, { Suspense } from 'react';

import Header from '@/components/ui/header';
import TranslationsProvider from '@/components/domain/TranslationProvider';
import LogoPage from '@/components/domain/LogoPage';

import i18nConfig from '../../../i18nConfig';
import { nunito_sans } from '../fonts';
import initTranslations from '../i18n';

import Loading from './loading';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const i18nNamespaces = ['commons', 'about'];
  const { resources } = await initTranslations(locale, i18nNamespaces);
  const links = [
    {
      name: 'Sobre mi',
      url: '/',
    },
    {
      name: 'Carrera',
      url: '/career',
    },
    {
      name: 'Proyectos',
      url: '/proyects',
    },
  ];

  return (
    <html className="dark" dir={dir(locale)} lang={locale}>
      <TranslationsProvider
        locale={locale}
        namespaces={i18nNamespaces}
        resources={resources}
      >
        <body className={nunito_sans.className}>
          <Suspense fallback={<Loading />}>
            <Header links={links} logo={<LogoPage />} />
            <div className="flex h-[calc(100vh_-_72px)] flex-col items-center justify-evenly">
              {children}
              <footer className="p-5 pt-10 opacity-50">
                <p>
                  {' '}
                  &copy;
                  {new Date().getFullYear()}
                  <span style={{ fontWeight: 'bold', marginLeft: '5px' }}>
                    macu-dev
                  </span>
                  . All rights reserved.
                </p>
              </footer>
            </div>
          </Suspense>
        </body>
      </TranslationsProvider>
    </html>
  );
}
