import type { Metadata } from 'next';

import './globals.css';
import { dir } from 'i18next';

import Header from '@/components/ui/header';
import TranslationsProvider from '@/components/domain/TranslationProvider';
import LogoPage from '@/components/domain/LogoPage';

import i18nConfig from '../../../i18nConfig';
import { nunito_sans } from '../fonts';
import initTranslations from '../i18n';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const i18nNamespaces = ['commons', 'about'];
  const { resources } = await initTranslations(locale, i18nNamespaces);
  const links = [
    {
      name: 'Sobre mi',
      url: '/',
    },
    {
      name: 'Carrera',
      url: '/career',
    },
    {
      name: 'Proyectos',
      url: '/proyects',
    },
  ];

  return (
    <html className="dark h-screen" dir={dir(locale)} lang={locale}>
      <TranslationsProvider
        locale={locale}
        namespaces={i18nNamespaces}
        resources={resources}
      >
        <body className={nunito_sans.className + ' h-full'}>
          <Header links={links} logo={<LogoPage />} />
          <div className="flex h-[calc(100vh-54px)] flex-col items-center justify-evenly">
            {children}
            <footer>hola</footer>
          </div>
        </body>
      </TranslationsProvider>
    </html>
  );
}
